server:
  port: 8081

spring:
  application:
    name: ai-assistant-service
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID:senin-proje-id}
          location: us-central1
          api-key: ${GEMINI_API_KEY:senin-api-key}
          chat:
            options:
              model: gemini-1.5-pro-002
              temperature: 0.7
