server:
  port: 8081

spring:
  application:
    name: ai-assistant-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-default-placeholder-key-for-now}
      chat:
        options:
          model: gpt-3.5-turbo
